server:
  port: 8080

rabbitmq:
  host: localhost
  port: 5672
  username: user
  password: pass
  connections:
    first:
      vhost: first
      queue: q1
    second:
      vhost: second
      queue: q2
